// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {utils} from '../models';

export function CreateAlertRule(arg1:models.AlertRule):Promise<void>;

export function DeleteAlertRule(arg1:number):Promise<void>;

export function GetAlertRules():Promise<Array<models.AlertRule>>;

export function GetAlerts(arg1:number):Promise<Array<models.Alert>>;

export function GetConfig():Promise<utils.Config>;

export function GetHistoryData(arg1:string,arg2:number):Promise<any>;

export function GetProcesses(arg1:string,arg2:string,arg3:number):Promise<Array<models.ProcessInfo>>;

export function GetSystemData():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<models.SystemInfo>;

export function KillProcess(arg1:number):Promise<void>;

export function UpdateAlertRule(arg1:models.AlertRule):Promise<void>;

export function UpdateConfig(arg1:utils.Config):Promise<void>;
