// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAlertRule(arg1) {
  return window['go']['main']['App']['CreateAlertRule'](arg1);
}

export function DeleteAlertRule(arg1) {
  return window['go']['main']['App']['DeleteAlertRule'](arg1);
}

export function GetAlertRules() {
  return window['go']['main']['App']['GetAlertRules']();
}

export function GetAlerts(arg1) {
  return window['go']['main']['App']['GetAlerts'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetHistoryData(arg1, arg2) {
  return window['go']['main']['App']['GetHistoryData'](arg1, arg2);
}

export function GetProcesses(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetProcesses'](arg1, arg2, arg3);
}

export function GetSystemData() {
  return window['go']['main']['App']['GetSystemData']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function UpdateAlertRule(arg1) {
  return window['go']['main']['App']['UpdateAlertRule'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}
